# fly.toml app configuration file generated for red-water-7719 on 2023-10-12T10:41:56-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "red-water-7719"
primary_region = "mia"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
